### ISSUE TITLE
PC项目无法正常结束进程

### ISSUE THREAD

**Issue by MXJ-Github** [HenJigg/WPF-Xamarin-Blazor-Examples#1]
大神~运行PC项目在登录页直接点“X”关闭进程无法结束。这个是我姿势不对还是确实是BUG呀？注：我拉取项目后直接运行没有初始化数据库。

**Comment by HenJigg** [comment]
这快还没有处理，😅

已从 Outlook Mobile<https://aka.ms/blhgte> 发送

________________________________
