### ISSUE TITLE
Consumption.Mobile.Android项目生成报错，DB还原不了

### ISSUE THREAD

**Issue by neillengh** [HenJigg/WPF-Xamarin-Blazor-Examples#3]
1、DB迁移失败，只有failed，没有其他提示信息。。。
PM> update-database
Build started...
Build failed.

2、Consumption.Mobile.Android项目生成报错，信息如下：
由于 MAX_PATH 未能为类  Android.Support.V4.View.AsyncLayoutInflater/IOnInflateFinishedListenerImplementor  生成  Java  类型: System.IO.DirectoryNotFoundException: 未能找到路径“C:\Users\neill\Desktop\WPF-Xamarin-Blazor-Examples-master\WPF-Xamarin-Blazor-Examples-master\src\Consumption\Consumption.Mobile\Consumption.Mobile.Android\obj\Debug\90\android\src\mono\android\support\v4\view\AsyncLayoutInflater_OnInflateFinishedListenerImplementor.java”的一部分。
   在 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   在 System.IO.File.InternalDelete(String path, Boolean checkHost)
   在 System.IO.File.Delete(String path)
   在 Xamarin.Android.Tools.Files.CopyIfStreamChanged(Stream stream, String destination)
   在 Xamarin.Android.Tasks.GenerateJavaStubs.CreateJavaSources(IEnumerable`1 javaTypes, TypeDefinitionCache cache)	Consumption.Mobile.Android			

但是该安装的我都安装了啊。。。。

**Comment by HenJigg** [comment]
你尝试把Mobile相关的内容卸载之后, 进行迁移试试

**Comment by neillengh** [comment]
> 你尝试把Mobile相关的内容卸载之后, 进行迁移试试

PM> update-database
Build started...
Build succeeded.
Unable to create an object of type 'ConsumptionContext'. For the different patterns supported at design time, see https://go.microsoft.com/fwlink/?linkid=851728
卸载后，显示的是数据库迁移成功，同时报错，但是mysql里没有生成数据库notedb

**Comment by wenchi** [comment]
先执行Add-Migration +name. 再执行update-database。一是作者教程这步没讲详细，二是你没去学下EF的使用
