### ISSUE TITLE
update-database出错

### ISSUE THREAD

**Issue by unicorn1009** [HenJigg/WPF-Xamarin-Blazor-Examples#4]
克隆下来整个项目，使用visual studio 2019初始化数据库时，执行update-database出错，显示：
Build started...
Build failed.
![image](https://user-images.githubusercontent.com/39911458/92991526-0549d880-f517-11ea-99d5-eb6ab1a80942.png)

**Comment by unicorn1009** [comment]
拉去了最新版本，执行update-database后报语法错误
![image](https://user-images.githubusercontent.com/39911458/93010574-ae98d900-f5c0-11ea-9291-3bcfeb42873d.png)

**Comment by wenchi** [comment]
先执行Add-Migration
